os: linux
dist: xenial
language: erlang
script: make all

_latest_otp_release: &latest_otp_release
  otp_release: 22.3

jobs:
  include:
    - name: Coverage Report
      language: erlang
      <<: *latest_otp_release
      env: COVER=true
      script: make test
      after_success:
        - for f in _build/test/covertool/*.xml; do cp "$f" $(basename "${f%.xml}.coverage.xml"); done
        - bash <(curl -s https://codecov.io/bash)
    - name: Test Examples
      language: erlang
      <<: *latest_otp_release
      script: make test-examples
    - otp_release: 22.3
    - otp_release: 22.0
    - otp_release: 21.3
    - otp_release: 21.0
    - otp_release: 20.3
    - otp_release: 20.0
    - otp_release: 19.3

cache:
   directories:
   - .plt
