os: linux
dist: xenial
language: erlang
script: "make all"
branches:
  only:
    - develop

otp_release:
   - 22.3
   - 22.0
   - 21.3
   - 21.0
   - 20.3
   - 20.0
   - 19.3

# coverage tests
jobs:
  include:
    - language: erlang
      otp_release: 22.3
      env: COVER=true
      after_success:
        - for f in _build/test/covertool/*.xml; do cp "$f" $(basename "${f%.xml}.coverage.xml"); done
        - bash <(curl -s https://codecov.io/bash)

cache:
   directories:
   - .plt
